apworld: https://github.com/silasary/Archipelago/releases/download/keymasters_keep-2.1.2/keymasters_keep.apworld

game_repos:
  - url: https://github.com/SerpentAI/KeymastersKeepGameArchive
    # This is the archived repo for pre-1.0 games. A bunch of them will be replaced by repos later in this list.
    # It must be the first entry.
    skip:
      - the_bazaar_game.py  # Outdated live service game
      - realm_of_the_mad_god_game.py  # Broken
      - cnc_generals_zh.py  # Fails fuzzing
      - unreal_tournament_game_of_the_year_edition_game.py  # renamed to unreal_tournament_game.py
      - quake_three_game.py  # Broken

  - url: https://github.com/ant-acres/KeyMastersKeepGames
  - url: https://github.com/ansem5/keymasters-keep-games
  - url: https://github.com/alxamei/KeymastersKeepGames
    glob: "games/*.py"
  - url: https://github.com/ArcherestArcher/KeymastersKeepImplementations
  - url: https://github.com/BowserCrusher/BowserKeymastersKeepGames
  - url: https://github.com/brev95/keymasters_keep
  - url: https://github.com/CaptainMcGee/McGeeKeymastersKeepGames
    skip:
      - cnc_generals_zh.py  # Fails fuzzing

  - url: https://github.com/CodeSystem521/Kmk-by-Code
  - url: https://github.com/delcake/KeymastersKeepGames
    glob: "**/*.py"

  - url: https://github.com/deyoungbryce/KeymastersKeepGames
    glob: "games/*.py"

  - url: https://github.com/eiron/KeymastersKeepGames
    skip:
      - cursed_red_dead_redemption_2_game.py
      - playnite_library.py
      - steam_achievements_game.py
  - url: https://github.com/ElireFeltores/KeymastersKeepMinesweeperPlus
  - url: https://github.com/Emeraldheart-Dev/Keymasters-Projects
  - url: https://github.com/Endivine1337/KeymastersKeepGames
  - url: https://github.com/erbs-gh/KeymastersKeepGames
  - url: https://github.com/flower-snek/KeymastersKeepGames/
  - url: https://github.com/g0m/KeymastersKeepGames
  - url: https://github.com/gamefalor/keymasters-Keep
  - url: https://github.com/Gameplushy/KeymastersKeepGames
  - url: https://github.com/jack5github/Jack5-Keymasters-Keep
    glob: keymasters_keep/*.py
  - url: https://github.com/jade152/KeyMastersKeepGames
    glob: "**/*.py"
    skip:
      - quake_three_game.py  # Broken
  - url: https://github.com/Knuxfan24/KnuxKeep
  - url: https://github.com/Kroooga/KeymastersKeepGames
  - url: https://github.com/LikeToCodeStreams/KeymastersKeepGames
  - url: https://github.com/lorebum1/KeymasterKeepGames
  - url: https://github.com/ManNamedGarbo/KeymastersKeepGames
    glob: "*.py"

  - https://github.com/MaynithTea/keymasters-keep-games
  - https://github.com/MediocreNightmare/GarfaxKeep

  - url: https://github.com/mathstar/KeymastersKeepGames
    skip:
      steam_library.py: True  # Accesses the Steam API during generation

  - https://github.com/NitroTears/KeymastersKeepGames
  - https://github.com/pamymaf/KeymastersKeepGames
  - https://github.com/Pantscada/keymasterskeepgames
  - https://github.com/pokemonfan1937/keymasterskeep
  - https://github.com/Rooby-Roo/KeymastersKeepGameArchive
  - https://github.com/RaceProUK/WestsideKeep
  - https://github.com/Seatori/KeymastersKeepGames
  - https://github.com/SerpentAI/KeymastersKeepGames
  - https://github.com/silasary/SilasaryKeep
  - url: https://github.com/Silvris/KeymastersKeepGames
    skip:
      - custom_medley_game.py  # Breaks tooling in interesting ways
  - https://github.com/Sundia1908/KeymastersKeepGames
  - https://github.com/Tetratic/KeyMastersKeepGames

  - url: https://github.com/Toad-99/KeymastersKeepGames
    # skip:
    #   - sea_of_thieves_game.py  # Broken

  - https://github.com/Venumii/KeymastersKeepGames
use_submodules: true
